#设置端口号
server:
  port: 8888  #，开发环境的HTTPS服务器大多会选这个端口

  #ssl:
  #key-store: file:///path/to/mykeys.jks      #属性指向密钥存储文件的存放路径 这里用了一个file://开头的URL， 从文件系统里加载该文件。你
  #key-store-password: letmein     #设置为创建该文 件时给定的密码。
  #key-password: letmein
  servlet:
    context-path: /yingx


#在自动配置DataSource Bean的时候，Spring Boot会使用这里的连接数据。
#DataSource Bean是一个连接池，如果Classpath里有Tomcat的连接池DataSource，那么就会使用这个连接池；
#否则，Spring Boot会在Classpath里查找以下连接池：   HikariCP  Commons DBCP    Commons DBCP 2
#配置数据源
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource                  #数据源连接池
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC      #url  8.0以后防止乱码需要加上
    username: root                                                #用户名
    password: 302767241                                           #密码
    driver-class-name: com.mysql.cj.jdbc.Driver                   #通常不需要设置驱动  Spring Boot会根据数据库URL识别出需要的驱动

    #.配置redis
  redis:
    host: 192.168.32.151   #ip地址
    port: 6379   #端口号
    database: 1   #操作的库
  #连接es
  data:
    elasticsearch:
      cluster-nodes: 192.168.32.151:9300
  #视图跳转
  mvc:
    view:
      prefix: /                                     #前缀
      suffix: .jsp                                  #后缀

  servlet:
    multipart:
      max-file-size: 100MB     #单个文件大小       默认1MB
      max-request-size: 900MB #同时上传多个文件大小 默认10MB
  #支持彩色日志
  output:
    ansi:
      enabled: always

  # 禁用模板缓存 确保这个文件不会发布到生产环境，否则生产环境里的应用程序就无法享受模板缓 存带来的性能提升
  thymeleaf:
    cache: false


#nybatis配置
mybatis:
  type-aliases-package: com.zhanghui.yx.entity              #指定实体类的位置
  mapper-locations: classpath:mapper/*.xml                  #mapper文件的位置

logging:                                          #运行日志配置
  file: yingx.log                              #日志写入的文件名
  level:
    root: info                                    #根日志的级别
    com.zhanghui.dao: debug                       #子日志



#自定义配置类
aliyunvo:
  endpoint:        https://oss-cn-beijing.aliyuncs.com
  accessKeyId:     LTAI4GKk9sRLQBP25dBYBmkE
  accessKeySecret: M7B1dHqF5leZOYrHfxZVRyfofG9sfp
  bucketName:       yingx-zh

#短信发送自定义配置
message:
  accessKeyId:  LTAI4GKk9sRLQBP25dBYBmkE
  accessKeySecret: M7B1dHqF5leZOYrHfxZVRyfofG9sfp
  messageSignatures: 应学
  template: SMS_195570824









